import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "@/components/footer";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { AppSidebar } from "@/components/app-sidebar"
import { NavigationMenu } from "@/components/navigationMenu";
import {
  SidebarInset,
  SidebarProvider,
} from "@/components/ui/sidebar"
import CustomTrigger from "@/components/CustomTrigger"
import { AuthProvider } from "@/contexts/AuthContext"
import { Toaster } from "sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "正豐皮號",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen flex flex-col`}
      >
        <AuthProvider>
          <div className="flex md:hidden">
            <SidebarProvider className="flex flex-col">
              <div className="sticky top-0 z-50 bg-white/90 flex items-center">
                <AppSidebar />
                <CustomTrigger />
                <Link href="/" className="">
                  <Image src="/images/logo1.png" width={120} height={100} alt="logo" />
                </Link>
              </div>

              <SidebarInset>
                {children}
              </SidebarInset>
            </SidebarProvider>
          </div>

          {/* Large screen: Show NavigationMenu */}
          <div className="hidden md:flex justify-center w-full">
            <div className="flex flex-col w-full">
              <div className="sticky top-0 z-50 bg-white/90 flex space-x-8 py-4 px-20">
                <Link href="/">
                  <Image src="/images/logo1.png" width={120} height={100} alt="logo" />
                </Link>
                <NavigationMenu />
              </div>

              {children}
            </div>
          </div>

          <Footer />
          <Toaster position="top-center" />
        </AuthProvider>
      </body>
    </html>
  );
}