import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "@/components/footer";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { AppSidebar } from "@/components/app-sidebar"
import { NavigationMenu } from "@/components/navigationMenu";
import { SidebarProvider  } from "@/components/ui/sidebar"
import CustomTrigger from "@/components/CustomTrigger"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "正豐皮號",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >

        <div className="flex md:hidden">
          <SidebarProvider className="flex flex-col">
            <div className="flex items-center">
              <AppSidebar />
              <CustomTrigger />
              <Link href="/" className="">
                <Image src="/images/logo1.png" width={120} height={100} alt="logo" />
              </Link>
            </div>

            {children}
          </SidebarProvider>
        </div>

        {/* Large screen: Show NavigationMenu */}
        <div className="hidden md:flex justify-center w-full px-6">
          <div className="flex flex-col">
            <div className="flex space-x-8 py-4">
              <Link href="/">
                <Image src="/images/logo1.png" width={120} height={100} alt="logo" />
              </Link>
              <NavigationMenu />
            </div>

            {children}
          </div>

        </div>

        <Footer />
      </body>
    </html>
  );
}
